apiVersion: v1
kind: Service
metadata:
  name: shedproj
spec:
  type: LoadBalancer
  selector:
    app: shedproj
  ports:
  - port: 8080
    targetPort: 8000
    nodePort: 31988
---
apiVersion: v1
kind: Service
metadata:
  name: static-resources
spec:
  selector:
    app: static-resources
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    NodePort: 32027
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: static-resources
spec:
  selector:
    matchLabels:
      app: static-resources
  template:
    metadata:
      labels:
        app: static-resources
    spec:
      containers:
      - name: static-resources
        image: anarabbasov/staticserver:1.3.2
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
---              
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shedproj
spec:
  selector:
    matchLabels:
      app: shedproj
  template:
    metadata:
      labels:
        app: shedproj
    spec:
      containers:
      - name: shedproj
        image: anarabbasov/shedproj:1.7.1
        env:
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: my-secret
              key: username
        - name: DB_PWD
          valueFrom:
            secretKeyRef:
              name: my-secret
              key: password
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
      
      
      
      
        



  
