# Generated by Django 4.1 on 2024-07-12 04:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("simplepwd", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="passwords",
            name="resource",
        ),
        migrations.AddField(
            model_name="passwords",
            name="name",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="simplepwd.resource",
            ),
        ),
    ]
