# Generated by Django 4.1 on 2024-07-16 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("simplepwd", "0002_remove_passwords_resource_passwords_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resource",
            name="name",
            field=models.CharField(max_length=256, unique=True),
        ),
    ]
